# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_busybody', '0002_auto_20170513_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='from_email',
            field=models.EmailField(default='none@none.jp', max_length=254),
            preserve_default=False,
        ),
    ]
