# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_busybody', '0003_emaillog_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcategory',
            name='display_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.TextField(),
        ),
    ]
