# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_busybody', '0004_auto_20170516_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaiveLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_id', models.CharField(max_length=256, unique=True)),
                ('when_acquired', models.FloatField()),
                ('when_expired', models.FloatField()),
            ],
        ),
    ]
