# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_busybody', '0005_naivelock'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
