# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfield',
            name='comma_separated_integer',
        ),
    ]
