# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_allfield_comma_separated_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('without_encrypt', models.CharField(max_length=256)),
                ('with_encrypt', models.CharField(max_length=256)),
                ('without_encrypt_with_log', models.CharField(max_length=256)),
                ('with_encrypt_with_log', models.CharField(max_length=256)),
            ],
        ),
    ]
