# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_encrypttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfield',
            name='_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='big_integer',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='char',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='file_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='generic_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='integer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='many_to_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='_allfield_many_to_many_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='one_to_one',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='positive_integer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='positive_small_integer',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='small_integer',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allfield',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
